In [1]:
import numpy as np

# Define two custom numpy arrays A and B
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[1, 2], [5, 6], [7, 8]])

# Stack vertically
stacked_vertical = np.vstack((A, B))

# Stack horizontally
stacked_horizontal = np.hstack((A, B))

print(stacked_vertical)
print(stacked_horizontal)

[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [5 6]
 [7 8]]
[[1 2 1 2]
 [3 4 5 6]
 [5 6 7 8]]


In [2]:
# Find intersection of A and B
common_elements = np.intersect1d(A, B)
print(common_elements)

[1 2 5 6]


In [3]:
numbers_in_range = A[(A >= 5) & (A <= 10)]
print(numbers_in_range)

[5 6]


In [4]:
import urllib.request

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
response = urllib.request.urlopen(url)

# Read the data using np.genfromtxt
iris_2d = np.genfromtxt(response, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

# Filter rows where petallength > 1.5 and sepallength < 5.0
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print(filtered_rows)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [5]:
import pandas as pd

# Load the Cars93 dataset
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Filter every 20th row starting from the first
filtered_rows = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

print(filtered_rows)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [6]:
# Replace missing values in Min.Price and Max.Price columns with column means
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

print(df[['Min.Price', 'Max.Price']])

    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]


In [7]:
# Generate a DataFrame
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Get rows with row sum greater than 100
rows_with_sum_gt_100 = df[df.sum(axis=1) > 100]

print(rows_with_sum_gt_100)

     0   1   2   3
0   39  34  33  35
1   30  32  39  17
2   23  27  37  36
3   31  37  23  30
4   15  28  34  28
9   39  18  37  11
13  22  32  26  34
14  37  13  37  23
